# Load standard Bash defaults
[ -f /etc/bashrc ] && . /etc/bashrc

# Prompt
BLUE='\[\e[34m\]'
RESET='\[\e[0m\]'
PS1="(\u@\h) \w\n${BLUE}>${RESET} "

# History
export HISTCONTROL=ignoreboth:erasedups
shopt -s histappend

# Load Shared Config
[[ -f ~/.shell_common ]] && source ~/.shell_common
