-- basic Vim options
vim.opt.mouse = "a"
vim.opt.tabstop = 4
vim.opt.shiftwidth = 4
vim.opt.softtabstop = 4
vim.opt.expandtab = true
vim.opt.splitright = true
vim.opt.splitbelow = true
vim.opt.smartindent = true
vim.opt.smartcase = true
vim.opt.cindent = true
vim.opt.autochdir = true
vim.opt.laststatus = 3
vim.opt.cmdheight = 1
vim.opt.showmatch = true
vim.opt.hlsearch = true
vim.opt.showmode = false
vim.opt.spell = true
vim.opt.spelllang = { "cjk", "en_us" }
vim.opt.undofile = true
vim.opt.wrap = true
vim.opt.linebreak = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.numberwidth = 4
vim.opt.breakindent = true
vim.opt.fileencoding = "utf-8"
vim.opt.signcolumn = "yes"
vim.opt.foldmethod = "marker"
vim.opt.foldcolumn = "0"
vim.g.tex_flavor = "latex"
vim.opt.fillchars = { fold = " ", vert = "│", eob = " ", msgsep = "‾" }
vim.g.netrw_liststyle = 3
vim.opt.termguicolors = true -- enable true color
